name: Deploy or Destroy AWS Lambda on develop

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      AWS_ACCOUNT_ID: 757367947438
      TF_ACTION: apply # Altere para "apply" ou "destroy"
      SQS_NAME: feedback_urgente-sqs
      SQS_DLQ_NAME: feedback_urgente-dlq


    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Autenticar com AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::757367947438:role/GitHubOIDCRole
          aws-region: us-east-1

      - name: Verificar modo de operação
        run: echo "Iniciando workflow em modo $TF_ACTION"

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Inicializar Terraform
        working-directory: infra
        run: terraform init

      - name: Validar Terraform
        working-directory: infra
        run: terraform validate

      - name: Verificar existência de SQS
        id: sqs_check
        run: |
          set +e
          SQS_URL=$(aws sqs get-queue-url --queue-name "$SQS_NAME" --region "$AWS_REGION" --query 'QueueUrl' --output text 2>/dev/null)
          SQS_DLQ_URL=$(aws sqs get-queue-url --queue-name "SQS_DLQ_NAME" --region "$AWS_REGION" --query 'QueueUrl' --output text 2>/dev/null)
          set -e

          if [ -n "$SQS_URL" ]; then
            echo "✅ SQS encontrado: $SQS_URL"
            echo "sqs_exists=true" >> $GITHUB_OUTPUT
            echo "sqs_url=$SQS_URL" >> $GITHUB_OUTPUT
          else
            echo "⚠️ SQS não encontrado."
            echo "sqs_exists=false" >> $GITHUB_OUTPUT
          fi
          
          if [ -n "$SQS_URL" ]; then
            echo "✅ SQS DQL encontrado: SQS_DLQ_URL"
            echo "sqs_dql_exists=true" >> $GITHUB_OUTPUT
            echo "sqs_dql_url=SQS_DLQ_URL" >> $GITHUB_OUTPUT
          else
            echo "⚠️ SQS DQL não encontrado."
            echo "sqs_dql_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Importar SQS se existir
        if: steps.sqs_check.outputs.sqs_exists == 'true'
        working-directory: infra
        run: |
          echo "Importando SQS para o estado..."
          terraform import aws_sqs_queue.feedback_urgente "${{ steps.sqs_check.outputs.sqs_url }}"

      - name: Importar SQS DQL se existir
        if: steps.sqs_check.outputs.sqs_dql_exists == 'true'
        working-directory: infra
        run: |
          echo "Importando SQS DQL para o estado..."
          terraform import aws_sqs_queue.dlq_feedback "${{ steps.sqs_check.outputs.sqs_dql_url }}"


      - name: Executar destroy da SQS
        if: env.TF_ACTION == 'destroy' && steps.sqs_check.outputs.sqs_exists == 'true'
        working-directory: infra
        run: |
          echo "Destruindo SQS..."
          terraform destroy -target=aws_sqs_queue.feedback_urgente -auto-approve

      - name: Executar destroy da SQS DQL
        if: env.TF_ACTION == 'destroy' && steps.sqs_check.outputs.sqs_dql_exists == 'true'
        working-directory: infra
        run: |
          echo "Destruindo SQS DQL..."
          terraform destroy -target=aws_sqs_queue.dlq_feedback -auto-approve

      - name: Executar apply da SQS
        if: env.TF_ACTION == 'apply' && steps.sqs_check.outputs.sqs_exists == 'false'
        working-directory: infra
        run: |
          echo "Criando SQS..."
          terraform apply -target=aws_sqs_queue.feedback_urgente -auto-approve

      - name: Executar apply da SQS DQL
        if: env.TF_ACTION == 'apply' && steps.sqs_check.outputs.sqs_dql_exists == 'false'
        working-directory: infra
        run: |
          echo "Criando SQS DQL..."
          terraform apply -target=aws_sqs_queue.dlq_feedback -auto-approve